spring:
  application:
    name: sistema
  datasource:
    driverClassName: com.mysql.cj.jdbc.Drive
    url: jdbc:mysql://localhost:3306/sistema
    username: 'myuser'
    password: 'secret'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true